export const CourseCategories = [
  "Executive",
  "Developer",
  "IT professional",
  "Data professional",
  "Security professionals",
  "Sales",
  "Customer service",
  "Faculty",
  "Non-profit",
  "Student",
];

export const MicrosoftColors = {
  darkBlue: "#2A446F",
  Blue: "#0078D4",
  lightBlue: "#8DC8E8",
  Peach: "#FF9176",
  lightPeach: "#FFBBA8",
  warmWhite: "#FFF8F3",
};

export const allCountiesKenya = [
  "Mombasa",
  "Kwale",
  "Kilifi",
  "Tana River",
  "Lamu",
  "Taita/Taveta",
  "Garissa",
  "Wajir",
  "Mandera",
  "Marsabit",
  "Isiolo",
  "Meru",
  "Tharaka-Nithi",
  "Embu",
  "Kitui",
  "Machakos",
  "Makueni",
  "Nyandarua",
  "Nyeri",
  "Nairobi",
  "Kirinyaga",
  "Murang'a",
  "Kiambu",
  "Turkana",
  "West Pokot",
  "Samburu",
  "Trans Nzoia",
  "Uasin Gishu",
  "Elgeyo/Marakwet",
  "Nandi",
  "Baringo",
  "Laikipia",
  "Nakuru",
  "Narok",
  "Kajiado",
  "Kericho",
  "Bomet",
  "Kakamega",
  "Vihiga",
  "Bungoma",
  "Busia",
  "Siaya",
  "Kisumu",
  "Homa Bay",
  "Migori",
  "Kisii",
  "Nyamira",
];
